# Project Information
site_name: 中国跑跑卡丁车单机启动器
site_description: 中国跑跑卡丁车单机版启动器的使用说明文档，以及一些信息
site_url: https://yanygm.github.io/Launcher_V2
strict: true

# Repository Information
repo_name: 'yanygm/Launcher_V2'
repo_url: 'https://github.com/yanygm/Launcher_V2'
edit_uri: 'https://github.com/yanygm/Launcher_V2/edit/main/docs/{path}'

theme:
  name: 'material'
  static_templates:
    - 404.html
  language: 'zh'
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: grey
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  include_search_page: true
  search_index_only: true
  favicon: 'favicon.ico'
  icon: 'material/school'
  font:
    text: 'Fira Sans'
    code: 'Fira Mono'

nav:
  - 主页: index.md
  - 功能介绍: feature.md
  - 安装: installation.md
  - 使用: how_to_use.md
