name: Check Build
on:
  push:
    branches-ignore:
      - gh-pages
    paths:
      - 'src/**'
      - '.github/workflows/check.yml'
    paths-ignore:
      - 'src/*.md'
  pull_request:
    branches-ignore:
      - gh-pages
    paths:
      - 'src/**'
      - '.github/workflows/check.yml'
    paths-ignore:
      - 'src/*.md'
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Enter src directory
        run: cd src

      - name: Build win-x64
        run: dotnet build Launcher.csproj --configuration Debug --runtime win-x64
      - name: Build win-x86
        run: dotnet build Launcher.csproj --configuration Debug --runtime win-x86
      - name: Build win-arm64
        run: dotnet build Launcher.csproj --configuration Debug --runtime win-arm64
